<?php 
$this->headMeta()->append('<meta charset="utf-8">')->append('<meta name="keywords" content="HTML, CSS, XML, XHTML, JavaScript" />');
$this->headTitle()->append("test")->append("category");
?>

<div class="container">
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <h1>Hello, world!</h1>
      <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      <p><a href="#" class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
    </div>
</div>

<div class="container">
<h3>./tpl/Wwww/Test/Product.phtml</h3>
<?php echo $this->partial("Www/Test/Product", array('message'=> "这里调用的模板是：./tpl/Www/Test/Product.html"));?>
</div>

<div class="container">
<h3>./tpl/Wwww/Product.phtml</h3>
<?php echo $this->partial("Www/Product", array('message'=> "这里调用的模板是：./tpl/Www/Product.html"));?>
</div>

<div class="container">
<h3>这里是分页</h3>
<?php echo $this->paginationControl($this->paginator, "Www/Pagination", $this->requestParams);?>
</div>

<div class="container">
<h3>这里是url rewrite</h3>
<?php echo $this->url(array('productId'=>2222), 'product');?>
</div>

<div class="container">
<h3>这里是提交表单</h3>
<a href="<?php echo $this->url(array('action'=>"view-form"));?>">提交表单</a>
</div>

<div class="container">
    <h3>这里栅格系统</h3>
    <div class="row">
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
      <div class="col-xs-1">.col-xs-1</div>
    </div>
    <div class="row">
      <div class="col-xs-2">.col-xs-2</div>
      <div class="col-xs-10">.col-xs-10</div>
    </div>
    <div class="row">
      <div class="col-xs-3">.col-xs-3</div>
      <div class="col-xs-9">.col-xs-9</div>
    </div>
    <div class="row">
      <div class="col-xs-4">.col-xs-4</div>
      <div class="col-xs-4">.col-xs-4</div>
      <div class="col-xs-4">.col-xs-4</div>
    </div>
    <div class="row">
      <div class="col-xs-5">.col-xs-5</div>
      <div class="col-xs-7">.col-xs-7</div>
    </div>
    <div class="row">
      <div class="col-xs-6">.col-xs-6</div>
      <div class="col-xs-6">.col-xs-6</div>
    </div>
    <div class="row">
      <div class="col-xs-7">.col-xs-7</div>
      <div class="col-xs-5">.col-xs-5</div>
    </div>
    <div class="row">
      <div class="col-xs-8">.col-xs-8</div>
      <div class="col-xs-4">.col-xs-4</div>
    </div>
    <div class="row">
      <div class="col-xs-9">.col-xs-9</div>
      <div class="col-xs-3">.col-xs-3</div>
    </div>
    <div class="row">
      <div class="col-xs-10">.col-xs-10</div>
      <div class="col-xs-2">.col-xs-2</div>
    </div>
    <div class="row">
      <div class="col-xs-11">.col-xs-11</div>
      <div class="col-xs-1">.col-xs-1</div>
    </div>
    
</div>
