<!DOCTYPE HTML>
<html>
<?php echo $this->headTitle()->append("Site name");?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->headMeta();?>
<link rel="stylesheet" href="<?php echo $this->serverUrl();?>/css/jquery.mobile-1.3.1.min.css" />
<script src="<?php echo $this->serverUrl();?>/js/jquery-1.10.0.min.js"></script>
<script src="<?php echo $this->serverUrl();?>/js/jquery.mobile-1.3.1.min.js"></script>
<body>
<div data-role="page">
    <div data-role="header">
        <a href="#" data-icon="home">首页</a>
        <h1>Edit Contact</h1>
        <a href="#" data-icon="back" data-theme="b" data-rel="back">后退</a>
    </div><!-- /header -->
    <div data-role="content"> 
       <?php echo $this->content;?>
    </div><!-- /content -->
    <div data-theme="a" data-role="footer" data-position="fixed">
        Total time:<?php echo $this->totalTime();?>
    </div><!-- /footer -->
</div><!-- /page -->
</body>
</html>