<div class="content">
    <?php if($this->current!=$this->first):?>
    <a href="<?php echo $this->url(array_merge(
    $this->requestParams, array('page' => $this->first))); ?>" data-role="button" data-inline="true" data-icon="arrow-l" data-iconpos="left">第一页</a>
    <?php else:?>
    <a class="ui-disabled" data-role="button" data-inline="true" data-icon="arrow-l" data-iconpos="left">第一页</a>
    <?php endif; ?>
    <!-- Previous page link -->
    <?php if ($this->previous){ ?>
    <a href="<?php echo $this->url(array_merge(
    $this->requestParams, array('page' => $this->previous))); ?>" data-role="button" data-inline="true" data-icon="arrow-l" data-iconpos="left">前一页</a>
    <?php } else { ?>
    <a class="ui-disabled" data-role="button" data-inline="true" data-icon="arrow-l" data-iconpos="left">前一页</a>
    <?php } ?>
    <!-- Numbered page links -->
    <a class="current"><?php echo $this->current;?></a>
    <!-- Next page link -->
    <?php if ($this->next){ ?>
    <a href="<?php echo $this->url(
    array_merge($this->requestParams, array('page' => $this->next))); ?>" data-role="button" data-inline="true" data-icon="arrow-r" data-iconpos="right">后一页</a>
    <?php } else { ?>
    <a class="ui-disabled" data-role="button" data-inline="true" data-icon="arrow-r" data-iconpos="right">后一页</a>
    <?php } ?>
    <?php if($this->current!=$this->last):?>
    <a href="<?php echo $this->url(array_merge(
    $this->requestParams, array('page' => $this->last))); ?>" data-role="button" data-inline="true" data-icon="arrow-r" data-iconpos="right">最后一页</a>
    <?php else:?>
    <a class="ui-disabled" data-role="button" data-inline="true" data-icon="arrow-r" data-iconpos="right">最后一页</a>
    <?php endif; ?>
</div>
