<!DOCTYPE HTML>
<html>
<?php echo $this->headTitle()->append("Site name");?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<?php echo $this->headMeta();?>
<link href="<?php echo $this->serverUrl();?>/css/bootstrap.min.css" rel="stylesheet" media="screen">
<!-- Bootstrap theme -->
<link href="<?php echo $this->serverUrl();?>/css/bootstrap-theme.min.css" rel="stylesheet">
<!--[if lte IE 6]>
<link rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl();?>/css/bootstrap-ie6.css?1">
<![endif]-->
<!--[if lte IE 7]>
<link rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl();?>/css/ie.css">
<![endif]-->
<link href="<?php echo $this->serverUrl();?>/css/non-responsive.css" rel="stylesheet" media="screen">
<link href="<?php echo $this->serverUrl();?>/css/showLoading.css" rel="stylesheet" media="screen">
<script type="text/javascript" src="<?php echo $this->serverUrl();?>/js/jquery-1.10.2.min.js"></script>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="<?php echo $this->serverUrl();?>/js/html5shiv.js"></script>
<script src="<?php echo $this->serverUrl();?>/js/respond.min.js"></script>
<![endif]-->
<style type="text/css">
body {
    padding-top: 60px;
    padding-bottom: 40px;
}
/* 禁用响应式布局：重新设置container的宽度。如果没有后面三行的代码，在IE6环境下navbar-top会显示为940px宽度 */
.container,
.navbar-static-top .container,
.navbar-fixed-top .container,
.navbar-fixed-bottom .container {
    width:1140px;
}
</style>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="https://github.com/wqc200/dang-php-framework">dang-php-framework</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo $this->serverUrl();?>">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
    </div>
</div>
 
<? echo $this->content;?>
    
<div class="container">
Total time:<?php echo $this->totalTime();?>
</div>

<!-- js文件放在网页底部可以加快网页加载速度 -->
<script type="text/javascript" src="<?php echo $this->serverUrl();?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl();?>/js/jquery.showLoading.min.js"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl();?>/js/jquery.blockUI.js"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl();?>/js/bootbox.js"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl();?>/js/jquery.form.min.js"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl();?>/js/custom.js"></script>
    
<!--[if lte IE 6]>
<script type="text/javascript" src="<?php echo $this->serverUrl();?>/js/bootstrap-ie.js"></script>
<![endif]-->
<script type="text/javascript">
(function ($) {
  $(document).ready(function() {
    if ($.isFunction($.bootstrapIE6)) $.bootstrapIE6($(document));
  });
})(jQuery);
</script>
    
</body>
</html>